# Generated by Django 4.2.5 on 2023-10-24 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_created_at_item_description_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('bracelets', 'Bracelets'), ('dresses', 'Dresses'), ('earrings', 'Earrrings'), ('necklaces', 'Necklaces'), ('tshirts', 'Tshirts'), ('watches', 'Watches'), ('pants', 'Pants'), ('skirts', 'Skirts')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
