# Generated by Django 4.2.5 on 2023-11-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_profile_birth_remove_profile_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cartitem'),
        ),
    ]
