# Generated by Django 4.2.5 on 2023-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0019_promocode_users_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_cvv",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_expiration",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_number",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
