# Generated by Django 4.2.5 on 2023-11-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0021_remove_payment_user_remove_order_delivery_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="card_name",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
