# Generated by Django 4.2.5 on 2023-11-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0024_alter_profile_card_cvv_alter_profile_card_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="number_house",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
