# Generated by Django 4.2.5 on 2023-11-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0027_order_cart_copy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart_copy",
        ),
        migrations.AddField(
            model_name="order",
            name="cart_items_copy",
            field=models.ManyToManyField(
                related_name="order_copies", to="store.cartitem"
            ),
        ),
    ]
