# Generated by Django 4.2.5 on 2023-11-22 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0030_orderitem_order_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart_copy",
        ),
    ]
