# Generated by Django 4.2.5 on 2023-12-04 11:08

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0039_remove_profile_number2_alter_profile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="card_cvv2",
            field=creditcards.models.SecurityCodeField(
                max_length=4, null=True, verbose_name="CVV/CVC"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="card_expiry2",
            field=creditcards.models.CardExpiryField(
                null=True, verbose_name="Data de Validade"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="card_number2",
            field=creditcards.models.CardNumberField(
                max_length=25, null=True, verbose_name="Número do Cartão"
            ),
        ),
    ]
