# Generated by Django 4.2.5 on 2023-12-04 11:11

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0040_profile_card_cvv2_profile_card_expiry2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="card_cvv2",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="card_expiry2",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="card_number2",
        ),
        migrations.AlterField(
            model_name="profile",
            name="card_cvv",
            field=creditcards.models.SecurityCodeField(
                max_length=4, null=True, verbose_name="CVV/CVC"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="card_expiration",
            field=creditcards.models.CardExpiryField(
                null=True, verbose_name="Data de Validade"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="card_number",
            field=creditcards.models.CardNumberField(
                max_length=25, null=True, verbose_name="Número do Cartão"
            ),
        ),
    ]
