# Generated by Django 4.2.5 on 2023-12-04 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0043_profile_firssst_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="firssst_name",
        ),
    ]
