# Generated by Django 4.2.5 on 2023-10-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_cart_items_cart_item_cart_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.CharField(default='N/A', max_length=254),
        ),
    ]
