# Generated by Django 4.2.5 on 2023-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0020_alter_address_city_alter_address_postal_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_info",
        ),
        migrations.AddField(
            model_name="profile",
            name="card_cvv",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="card_expiration",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="card_number",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="street",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
