# Generated by Django 4.2.5 on 2023-11-15 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0022_profile_card_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="card_cvv",
            field=models.CharField(
                max_length=3,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{3}$", "Enter a valid CVV."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="card_expiration",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
