# Generated by Django 4.2.5 on 2023-11-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0025_profile_number_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
