# Generated by Django 4.2.5 on 2023-11-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0028_remove_order_cart_copy_order_cart_items_copy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart_items_copy",
        ),
        migrations.AddField(
            model_name="order",
            name="cart_copy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_copies",
                to="store.cartbase",
            ),
        ),
    ]
