# Generated by Django 4.2.5 on 2023-12-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0042_alter_profile_city_alter_profile_postal_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="firssst_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
