# Generated by Django 4.2.5 on 2023-12-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0044_remove_profile_firssst_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=15),
        ),
    ]
